version: 2.1

jobs:
  build-avr:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install AVR Toolchain"
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc-avr binutils-avr avr-libc make
      - run:
          name: "Build Firmware"
          command: make build
      - store_artifacts:
          path: blink.hex
          destination: blink.hex

workflows:
  avr-build-workflow:
    jobs:
      - build-avr